FROM openjdk:17
WORKDIR /internal-it-017/Hello.java
COPY . .
RUN javac Hello.java
CMD ["java", "Hello"]

                                                                                                                                                                                         
